-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('USER_CREATED', 'USER_STATUS_CHANGED', 'USER_EMAIL_CHANGED', 'USER_NAME_CHANGED', 'USER_PASSWORD_RESET', 'USER_ROLE_CHANGED', 'PROFILE_NAME_CHANGED', 'PROFILE_EMAIL_CHANGED', 'PROFILE_PASSWORD_CHANGED', 'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'NEWS_CREATED', 'NEWS_UPDATED', 'NEWS_SUBMITTED', 'NEWS_CHANGES_REQUESTED', 'NEWS_PUBLISHED', 'NEWS_ARCHIVED', 'NEWS_DELETED', 'NEWS_RESTORED', 'NEWS_CATEGORY_CREATED', 'TECHNOLOGY_CREATED', 'TECHNOLOGY_UPDATED', 'TECHNOLOGY_SUBMITTED', 'TECHNOLOGY_CHANGES_REQUESTED', 'TECHNOLOGY_PUBLISHED', 'TECHNOLOGY_ARCHIVED', 'TECHNOLOGY_DELETED', 'TECHNOLOGY_RESTORED', 'TECHNOLOGY_CATEGORY_CREATED', 'TECHNOLOGY_CERTIFICATION_CREATED', 'KNOWLEDGE_CREATED', 'KNOWLEDGE_UPDATED', 'KNOWLEDGE_SUBMITTED', 'KNOWLEDGE_CHANGES_REQUESTED', 'KNOWLEDGE_PUBLISHED', 'KNOWLEDGE_ARCHIVED', 'KNOWLEDGE_DELETED', 'KNOWLEDGE_RESTORED', 'KNOWLEDGE_CATEGORY_CREATED', 'LEARNING_CREATED', 'LEARNING_UPDATED', 'LEARNING_SUBMITTED', 'LEARNING_CHANGES_REQUESTED', 'LEARNING_PUBLISHED', 'LEARNING_ARCHIVED', 'LEARNING_DELETED', 'LEARNING_CATEGORY_CREATED', 'LOCATION_CREATED', 'LOCATION_UPDATED', 'LOCATION_VISIBILITY_CHANGED', 'LOCATION_DELETED', 'NETWORK_PARTNER_CREATED', 'NETWORK_PARTNER_UPDATED', 'NETWORK_PARTNER_DELETED', 'PROJECT_ORIGIN_SAVED', 'NEWS_MEDIA_UPLOADED', 'NEWS_MEDIA_ATTACHED', 'NEWS_MEDIA_DETACHED', 'TECHNOLOGY_MEDIA_ATTACHED', 'TECHNOLOGY_MEDIA_DETACHED', 'KNOWLEDGE_MEDIA_ATTACHED', 'KNOWLEDGE_MEDIA_DETACHED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;
-- AlterEnum
BEGIN;
CREATE TYPE "AuditResourceType_new" AS ENUM ('USER', 'PROFILE', 'NEWS', 'NEWS_CATEGORY', 'TECHNOLOGY', 'TECHNOLOGY_CATEGORY', 'TECHNOLOGY_CERTIFICATION', 'KNOWLEDGE', 'KNOWLEDGE_CATEGORY', 'LEARNING', 'LEARNING_CATEGORY', 'LOCATION', 'NETWORK_PARTNER', 'PROJECT_ORIGIN', 'NEWS_MEDIA');
ALTER TABLE "AuditLog" ALTER COLUMN "resourceType" TYPE "AuditResourceType_new" USING ("resourceType"::text::"AuditResourceType_new");
ALTER TYPE "AuditResourceType" RENAME TO "AuditResourceType_old";
ALTER TYPE "AuditResourceType_new" RENAME TO "AuditResourceType";
DROP TYPE "public"."AuditResourceType_old";
COMMIT;
-- DropForeignKey
ALTER TABLE "ProjectGoal" DROP CONSTRAINT "ProjectGoal_deletedById_fkey";
-- DropForeignKey
ALTER TABLE "ProjectObjective" DROP CONSTRAINT "ProjectObjective_deletedById_fkey";
-- DropForeignKey
ALTER TABLE "ProjectTimelineEntry" DROP CONSTRAINT "ProjectTimelineEntry_deletedById_fkey";
-- DropTable
DROP TABLE "ProjectGoal";
-- DropTable
DROP TABLE "ProjectObjective";
-- DropTable
DROP TABLE "ProjectTimelineEntry";
